### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mpapousGit** [mpapousGit/datalist#5]
- [ ] .gitignore to get rid of node_modules
- [ ] convert double quotes to single JS only
- [ ] remove iffies
- [ ] get rid of angular's array injection syntax
- [ ] spacing consistency
- [ ] error handling in your CSV service
- [ ] see how we can extract CSV parsing to the server
- [ ] change testFactory to service
